### ISSUE TITLE
Update screenshot to match proper name

### ISSUE THREAD

**Issue by ferdingler** [aws-samples/aws-serverless-cicd-workshop#12]
The screenshot shown here https://cicd.serverlessworkshops.io/buildpipe/done.html needs to be updated to show the correct name to match the pipeline. `ExecuteChangeSet` is now `Deploy`.

**Comment by hanish-garg** [comment]
Changing ExecuteChangeSet to deploy in verify pipeline image . please review.. (i have created a pull request)
