### ISSUE TITLE
CDK installation on Cloud9 causing version conflicts

### ISSUE THREAD

**Issue by rmalecky** [aws-samples/aws-serverless-cicd-workshop#13]
This relates to https://cicd.serverlessworkshops.io/buildpipe/cdkinit.html

The CDK is now installed on Cloud9 but it is a slightly out of date version.  On a C9 instance launched on 2020-05-09 I see CDK version 1.36.1, the current version of CDK is 1.38.0.

When I follow the instructs in the lab the current v1.38 construct libraries are being installed but the aws-cdk/core is version 1.36.1.  This causes an error when it trying to deploy the stack.

**Comment by ferdingler** [comment]
Thanks for reporting it @rmalecky . I will take a look

**Comment by ferdingler** [comment]
Fix has been published in the latest release #14
