### ISSUE TITLE
insufficient permissions to modify .profile when running bootstrap.sh

### ISSUE THREAD

**Issue by D1g1talW00d** [aws-samples/aws-serverless-cicd-workshop#32]
After deploying a new Cloud9 instance the /home/ec2-user/.profile file is owned by root so bootstrap.sh cannot update it at line 69. Had to change ownership of .profile to ec2-user to run bootstrap.sh. Would be good to have this mentioned in the guide.

**Comment by ferdingler** [comment]
Hi @D1g1talW00d, thanks for bringing this to our attention. This is the first time I hear about issues with directory permissions when bootstrapping. I'll look into this.

**Comment by ejschaefer** [comment]
@ferdingler - this might not be needed. Cloud9 EC2 environments (AWS provided AMI) include Homebrew/Linuxbrew. Also Linuxbrew/install was merged into Homebrew/install. I'm creating a new issue for the URL update

**Comment by ferdingler** [comment]
PR #37 has been merged to master.
