### ISSUE TITLE
SAM Init has additional question

### ISSUE THREAD

**Issue by curtisdarst** [aws-samples/aws-serverless-cicd-workshop#52]
During the SAM INIT section, there is a question that is not referenced in the document.

What package type would you like to use?
        1 - Zip (artifact is a zip uploaded to S3)
        2 - Image (artifact is an image uploaded to an ECR image repository)
Package type:

**Comment by msailes** [comment]
https://github.com/aws-samples/aws-serverless-cicd-workshop/pull/53

**Comment by ferdingler** [comment]
PR has been merged.
