### ISSUE TITLE
New SAM CLI

### ISSUE THREAD

**Issue by imyrvold** [aws-samples/aws-serverless-cicd-workshop#54]
This workshop is not working with the new AWS SAM introduced at AWS re:Invent 2020.
It would also be nice to have the workshop rewritten to support the new CDK Pipelines construct.

**Comment by ferdingler** [comment]
Hi @imyrvold , thanks for creating this issue. We have updated the instructions according to the new SAM CLI. Can you please confirm if this is what you are referring to? 

You can check out the updated instructions here: https://cicd.serverlessworkshops.io/javascript/sam/init.html
