### ISSUE TITLE
Build Failed / Error: 'nodejs12.x' runtime is not supported

### ISSUE THREAD

**Issue by nagasakitakaya** [aws-samples/aws-serverless-cicd-workshop#6]
https://cicd.serverlessworkshops.io/buildpipe/done.html
This URL, an error occurred during the build stage.

```
Build Failed
--
Error: 'nodejs12.x' runtime is not supported
```

To resolve this error, I changed the "aws / codebuild / amazon linux 2-x86_64-standard: 1.0" to 2.0 specified in the Docker image in pipeline.yml,
and updated the SAM CLI to the latest version in buildspec.yml.

**Comment by ferdingler** [comment]
Thanks for reporting! I will update this shortly

**Comment by ferdingler** [comment]
Issue has been fixed and deployed. Thanks again!
