### ISSUE TITLE
Update screenshot in sam init to choose Java 8

### ISSUE THREAD

**Issue by ferdingler** [aws-samples/aws-serverless-cicd-workshop#63]
https://cicd.serverlessworkshops.io/java/sam/init.html#type-12-to-select-the-java-8-runtime

While running sam init, the workshop says to choose option 12 to select Java 8, however, the correct option is 14 now. Need to update the screenshot to reflect the new options.

**Comment by msailes** [comment]
I'll fix this.

**Comment by ferdingler** [comment]
Thank you @msailes . #66
