### ISSUE TITLE
Rendering bug - workshop/content/java/buildpipe/pipeascode/build/_index.en.md

### ISSUE THREAD

**Issue by jsamuel1** [aws-samples/aws-serverless-cicd-workshop#72]
The Java workshop, PipeAsCode Build step has an expand section for "Click here to see how the entire file should look like".

When expanded, raw HTML is viewed, rather than formatted java.
It appears that the Hugo shortcode is not expanding correctly at workshop/content/java/buildpipe/pipeascode/build/_index.en.md line 48.

**Comment by brianz** [comment]
This workshop has been reorganized and this is no longer and issue.
