### ISSUE TITLE
Bootstrap.sh fails on upgrading aws-sam-cli on Amazon Linux 1

### ISSUE THREAD

**Issue by chrismckinnel** [aws-samples/aws-serverless-cicd-workshop#74]
Using the Cloud9 instance deployed in lab 2 for WildRydes, which is an Amazon Linux 1 instance, the bootstrap.sh script throws an error when trying to upgrade `aws-sam-cli`.

![image](https://user-images.githubusercontent.com/1034154/122289747-29739380-cf47-11eb-95b2-b00d30cec81c.png)

This is due to attempting to run `brew upgrade aws-sam-cli` when `aws-sam-cli` is not currently installed via brew.

Instead of attempting to upgrade `aws-sam-cli`, we should check if it's installed first.

```bash
# upgrade if aws-sam-cli is installed, install if not
set +e
brew ls --versions aws-sam-cli
if [ $? -eq 0 ]; then
    brew upgrade aws-sam-cli
else
    brew install aws-sam-cli
fi
set -e
```

This will result in a successful run (and an install via brew if it's not currently installed).

![image](https://user-images.githubusercontent.com/1034154/122290424-d221f300-cf47-11eb-8e34-3f87bc369752.png)

**Comment by brianz** [comment]
Fixed. Closing.
