### ISSUE TITLE
error in bootstrap.sh running "sudo ln -sf /bin/touch /usr/bin/touch"

### ISSUE THREAD

**Issue by hakanson** [aws-samples/aws-serverless-cicd-workshop#76]
When the `sudo ln -sf /bin/touch /usr/bin/touch` command runs from `bootstrap.sh`, the following error message appears on  the Cloud9 Terminal.

```bash
ln: 'bin/touch' and '/usr/bin/touch' are the same file
```

![console aws amazon com_cloud9_ide_3b67b91108124a5ea6859d3fe995fcef](https://user-images.githubusercontent.com/414500/131525947-e38c6b7a-8d3b-4b44-a743-c546ede67405.png)

Cloud9 IDE was created using Amazon Linux 2

Commenting out this line allows `bootstrap.sh` to run correctly.

**Comment by brianz** [comment]
Thanks for this report @hakanson 

Indeed, this script was written prior to Amazon Linux 2 and some steps need updating. We're in the middle of updating this and a new script which works on AL2 can be found in this branch:

https://github.com/aws-samples/aws-serverless-cicd-workshop/blob/sam-pipelines/workshop/static/assets/bootstrap.sh

I'd be happy to hear if that one works for you.

**Comment by mohamed-ali** [comment]
I confirm the new script works fine for amzn2.x86_64. It installs `SAM CLI, version 1.31.0`.
Could you merge to the main branch? 

Thanks.

**Comment by brianz** [comment]
Fixed. Closing.
