### ISSUE TITLE
aws-cdk-lib 2.0.0 requires constructs 10, the modules required by cdk are still versions that use constructs 3.x

### ISSUE THREAD

**Issue by beargolightly** [aws-samples/aws-serverless-cicd-workshop#84]
!NB!  I am not using Cloud9 per this tutorial - I am using Pycharm with a Python 3.9 in a venv.  I don't think this is relevant, but hey.

This is the requirements.txt from the current python cdk after cdk init:

    aws-cdk-lib==2.0.0
    constructs>=10.0.0,<11.0.0

However, [the modules required by this workshop](https://github.com/aws-samples/aws-serverless-cicd-workshop/blob/59eb02d1f841edd633a2025df957a24997189f79/workshop/content/python/buildpipe/cdkinit/_index.en.md?plain=1#L39) are all still on v1.134.0 and are dependent on v3-4 of the constructs library.

Everything works great up until you attempt to install that handful of modules, and then:

![image](https://user-images.githubusercontent.com/5595948/145119588-69eae9fb-0d91-4336-a42c-63134e3e4742.png)

Thoughts?

**Comment by brianz** [comment]
This workshop has been reorganized to use SAM Pipelines rather than CDK.

If you are still looking for a CDK reference you can find a working version [in the Appendix section](https://cicd.serverlessworkshops.io/appendix.html).
