### ISSUE TITLE
JavaScript workshop on Cloud9 comes with CDKV2

### ISSUE THREAD

**Issue by AlperSakarya** [aws-samples/aws-serverless-cicd-workshop#86]
Hello, the Javascript lab code and all the import constructs are for AWS CDK V1, however Cloud9 now comes with CDK V2 and the lab does not work if someone was to copy/paste all the instructions. It requires users to troubleshoot the error.

If we do not want to refactor the workshop,
One needs to remove AWS CDK V2 from the default Cloud 9 instance and install AWS CDK V1 and initiate the project that way, also an alias needed as "cdk" so the rest of the workshop commands functions properly. I will be submitting a pull request for it but can't find the Dev branch.

**Comment by brianz** [comment]
Fixed. Closing.
