### ISSUE TITLE
Java8 workshop getting errors

### ISSUE THREAD

**Issue by hanish-garg** [aws-samples/aws-serverless-cicd-workshop#89]
1. Got issue related to lab where it says do "Cdk bootstrap"
2. after doing cdk bootstrap running the command gives below error
3. it will be good to mention which POM.xml to update for adding maven dependencies - it should be pipeline pom but because there is pom in application code it would be a good idea to mention the pipeline pom

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project pipeline: Compilation failure: Compilation failure: 
[ERROR] /home/ec2-user/environment/sam-app/pipeline/src/main/java/com/myorg/PipelineStack.java:[3,35] package software.amazon.awscdk.core does not exist
[ERROR] /home/ec2-user/environment/sam-app/pipeline/src/main/java/com/myorg/PipelineStack.java:[4,35] package software.amazon.awscdk.core does not exist
[ERROR] /home/ec2-user/environment/sam-app/pipeline/src/main/java/com/myorg/PipelineStack.java:[5,35] package software.amazon.awscdk.core does not exist
[ERROR] /home/ec2-user/environment/sam-app/pipeline/src/main/java/com/myorg/PipelineStack.java:[8,36] cannot find symbol
[ERROR]   symbol: class Stack
[ERROR] /home/ec2-user/environment/sam-app/pipeline/src/main/java/com/myorg/PipelineStack.java:[9,32] cannot find symbol
[ERROR]   symbol:   class Construct
[ERROR]   location: class com.myorg.PipelineStack
[ERROR] /home/ec2-user/environment/sam-app/pipeline/src/main/java/com/myorg/PipelineStack.java:[13,32] cannot find symbol
[ERROR]   symbol:   class Construct
[ERROR]   location: class com.myorg.PipelineStack
[ERROR] /home/ec2-user/environment/sam-app/pipeline/src/main/java/com/myorg/PipelineStack.java:[13,72] cannot find symbol
[ERROR]   symbol:   class StackProps
[ERROR]   location: class com.myorg.PipelineStack
[ERROR] /home/ec2-user/environment/sam-app/pipeline/src/main/java/com/myorg/PipelineStack.java:[16,45] incompatible types: com.myorg.PipelineStack cannot be converted to software.constructs.Construct

**Comment by brianz** [comment]
This workshop has been reorganized to use SAM Pipelines. As such, CDK errors are no longer and issue.
