### ISSUE TITLE
Add support for nodejs16.x

### ISSUE THREAD

**Issue by allanchua101** [aws-samples/aws-serverless-cicd-workshop#91]
NodeJS 16 support for AWS Lambda has been [released back in May 12, 2022](https://aws.amazon.com/blogs/compute/node-js-16-x-runtime-now-available-in-aws-lambda/) and it would be cool to see it added on workshop SAM menus.

![Screenshot of Initialize Project Page](https://i.imgur.com/eKrif28.png)

NodeJS Tag: `nodejs16.x`

**Comment by brianz** [comment]
Fixed in https://github.com/aws-samples/aws-serverless-cicd-workshop/pull/92
